export const GET_REGISTERED_MAILS: string = 'GET_REGISTERED_MAILS';

export const GET_REGISTERED_MAILS_SUCCESS: string = 'GET_REGISTERED_MAILS_SUCCESS';

export const GET_REGISTERED_MAILS_ERROR: string = 'GET_REGISTERED_MAILS_ERROR';